/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A URI that can be used to flag a place or review for inappropriate
 *
 * @remarks
 * content. This is populated only when the grounding source is Google Maps.
 */
export type SourceFlaggingUri = {
  /**
   * The ID of the place or review.
   */
  source_id?: string | undefined;
  /**
   * The URI that can be used to flag the content.
   */
  flag_content_uri?: string | undefined;
};
